version: '3.1'

services:

  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: devdb

  adminer:
    image: adminer
    ports:
      - "8081:8080"